function randomAliases(empty: boolean = true) :: item:
	return random item out of any boots

test "any aliases random":
	assert (random itemtype out of 14, a diamond helmet, false and console) is a diamond helmet with "Could not grab the diamond helmet out of the list."
	assert (random itemtype out of 14, a diamond helmet, a gold helmet, false and console) is any helmet with "Could not grab any helmet out of the list."
	assert random item out of any boots is any boots with "Failed to return the same types as the list."
	set {_list::*} to true, any boots and false
	assert random number out of {_list::*} is not set with "Failed to error when finding incorrect type."
	loop 50 times:
		if randomAliases() is not randomAliases():
			stop
	assert false is true with "The aliases were the same 50 times in a row"

test "any number random":
	assert (random number out of 47, a diamond helmet, false and console) is 47 with "Could not grab the number out of the list."
