test "math order":
	assert 1 + 1 = 2 with "basic math failed"
	assert 5 - 3 = 2 with "basic math failed"

	assert 5 - 3 - 1 = 1 with "basic chained math failed"
	assert 5-3-2 = 0 with "basic chained math failed"
	assert 10 - 1 - 5 = 4 with "basic chained math failed"

	assert (9 - 1) - 3 = 5 with "basic chained math with parentheses failed"
	assert 9 - (1 - 3) = 11 with "basic chained math with parentheses failed"
