test "item amount of itemstack":
	set {_loc} to spawn of world "world"
	set {_old-block} to type of block at {_loc}
	set block at {_loc} to chest
	add 10 stone to inventory of block at {_loc}
	set {_item} to slot 0 of inventory of block at {_loc}
	assert item amount of {_item} is 10 with "Amount of itemstack is not 10: %{_amount}%"
	remove 1 from item amount of {_item}
	assert item amount of {_item} is 9 with "Amount of itemstack is not 9: %{_amount}%"
	set block at {_loc} to {_old-block}

test "item amount of itemtype":
	set {_item} to 10 stone
	set {_amount} to item amount of {_item}
	assert item amount of {_item} is 10 with "Amount of itemtype is not 10: %{_amount}%"
	remove 1 from item amount of {_item}
	assert item amount of {_item} is 9 with "Amount of itemtype is not 9: %{_amount}%"

test "item amount of slot":
	set {_loc} to spawn of world "world"
	set {_old-block} to type of block at {_loc}
	set block at {_loc} to chest
	add 10 stone to inventory of block at {_loc}
	assert item amount of (slot 0 of inventory of block at {_loc}) is 10 with "Amount of slot is not 10: %{_amount}%"
	remove 1 from item amount of (slot 0 of inventory of block at {_loc})
	assert item amount of (slot 0 of inventory of block at {_loc}) is 9 with "Amount of slot is not 9: %{_amount}%"
	set block at {_loc} to {_old-block}
