
# Test not related to a made issue. Details at pull request.
test "random integer test":
	assert random integer between 1 and 1 is 1 with "Random integer between 1 and 1 should be 1"
	assert random integer between 1.2 and 1.2 is not set with "Random integer between 1.2 and 1.2 shouldn't return anything"
	assert random integer between 1.2 and 1.3 is not set with "Random integer between 1.2 and 1.3 shouldn't return anything"
	assert random integer between 1.9 and 2.1 is 2 with "Random integer between 1.9 and 2.1 should be 2"
	assert random integer between 1.5 and 2 is 2 with "Random integer between 1 and 2 should be 2"
