test "item with fire resistance" when running minecraft "1.20.5":

	# single item
	set {_item} to diamond with fire resistance
	assert {_item} is fire resistant with "{_item} was not fire resistant"

	# multiple items
	set {_item} to fire resistant diamond
	set {_item2} to paper with fire resistance
	assert ({_item} and {_item2}) are fire resistant with "{_item} and {_item2} are unexpectedly not fire resistant"

	# TODO: add tests for already fire resistant items (i.e. netherite) in 1.21 (doesn't work in 1.20.5 or 1.20.6)
