test "portal cooldown":
	spawn zombie at spawn of world "world":
		assert event-entity's portal cooldown is 0 seconds with "entity spawned with a portal cooldown"
		set event-entity's portal cooldown to 25 ticks
		assert event-entity's portal cooldown is 25 ticks with "portal cooldown set failed"
		add 5 seconds to event-entity's portal cooldown
		assert event-entity's portal cooldown is 125 ticks with "portal cooldown add failed"
		remove 12 ticks from event-entity's portal cooldown
		assert event-entity's portal cooldown is 113 ticks with "portal cooldown remove failed"
		remove 999 ticks from event-entity's portal cooldown
		assert event-entity's portal cooldown is 0 ticks with "portal cooldown remove failed"
		delete event-entity's portal cooldown
		assert event-entity's portal cooldown is 0 ticks with "portal cooldown delete failed"
		reset event-entity's portal cooldown
		assert event-entity's portal cooldown is 15 seconds with "portal cooldown reset failed"
		delete event-entity
