test "glowing sign blocks" when running minecraft "1.17.1":
	set {_loc} to spawn of "world"
	set {_original block} to type of block at {_loc}
	set block at {_loc} to sign
	assert block at {_loc} doesn't have glowing text with "Sign had glowing text erroneously (1)"
	make block at {_loc} have glowing text
	assert block at {_loc} has glowing text with "Sign had normal text erroneously"
	make block at {_loc} have normal text
	assert block at {_loc} doesn't have glowing text with "Sign had glowing text erroneously (2)"
	set block at {_loc} to {_original block}

test "glowing sign items" when running minecraft "1.17.1":
	set {_sign} to floor sign
	assert {_sign} doesn't have glowing text with "Sign had glowing text erroneously (1)"
	make {_sign} have glowing text
	assert {_sign} has glowing text with "Sign had normal text erroneously"
	make {_sign} have normal text
	assert {_sign} doesn't have glowing text with "Sign had glowing text erroneously (2)"
