test "vector rotate around axis":

	set {_v} to vector(1, 1, 1)
	rotate {_v} around y axis by 90 degrees
	assert {_v} is vector(1, 1, -1) with "rotate around y vector failed (expected %vector(1, 1, -1)%, got %{_v}%)"

	rotate {_v} around x axis by -90 degrees
	assert {_v} is vector(1, -1, -1) with "rotate around x vector failed (expected %vector(1, -1, -1)%, got %{_v}%)"

	rotate {_v} around z axis by -90 degrees
	assert {_v} is vector(-1, -1, -1) with "rotate around z vector failed (expected %vector(-1, -1, -1)%, got %{_v}%)"
