test "SecConditional - ParseIf":
	parse if plugin "LaDeDa-LeFakePlugin" is enabled:
		#this code in this section should NOT be parsed
		floopidy flopidy flernindurf
		assert 10 = 1 with "ParseIf section was parsed and failed"

	else parse if plugin "Skript" is enabled:
		#this code in this should SHOULD be parsed
		set {_a} to 10 # I mean.. what else do you put here, amirite?

	else:
		#this code in this section SHOULD be parsed but should NOT be ran
		assert 10 = 1 with "ParseIf/Else section was parsed and failed"

test "SecConditional":
	set {_b} to true
	if 1 is 1:
		delete {_b}
		1 = 2
	else if 1 = 1:
		assert 1 = 2 with "conditional failed ##1"
	else:
		assert 1 = 2 with "conditional failed ##2"
	if {_b} is set:
		assert 1 = 2 with "conditional failed ##3"

	if 1 = 2:
		assert 1 = 2 with "conditional failed ##4"
	else if 1 = 1:
		exit 1 section
	else:
		assert 1 = 2 with "conditional failed ##5"

test "SecConditional - if all true":
	if:
		1 is 1
		2 is 2
	then:
		set {_a} to true
	assert {_a} is set with "if all did not run"

test "SecConditional - if all false":
	if:
		1 is 1
		2 is 1
	then:
		set {_a} to true
	assert {_a} is not set with "if all ran when conditions were false"

test "SecConditional - if any true":
	if any:
		1 is 3
		2 is 2
	then:
		set {_a} to true
	assert {_a} is set with "if any did not run when at least one condition was true"

test "SecConditional - if any false":
	if any:
		1 is 3
		2 is 7
	then:
		set {_a} to true
	assert {_a} is not set with "if any ran when no condition was true"


test "SecConditional - if any else":
	if any:
		1 is 3
		2 is 7
	then:
		set {_a} to true
	else:
		set {_a} to false
	assert {_a} is false with "if any did not run else when no condition was true"

test "SecConditional - if all else":
	if all:
		1 is 3
		2 is 7
	then:
		set {_a} to true
	else:
		set {_a} to false
	assert {_a} is false with "if all did not run else when at least one condition was false"

test "SecConditional - if all by default":
	if:
		1 is 2
		2 is 7
	then:
		set {_a} to true
	assert {_a} is not set with "bare 'if' did not require all conditions to be true"

test "SecConditional - else if all true":
	if:
		1 is 2
		2 is 7
	then:
		set {_a} to true
	else if:
		1 is 1
		2 is 2
	then:
		set {_a} to false
	assert {_a} is false with "'else if all' did not run when preceding 'if' was false and conditions were true"

test "SecConditional - else if any true":
	if:
		1 is 2
		2 is 7
	then:
		set {_a} to true
	else if any:
		1 is 1
		2 is 7
	then:
		set {_a} to false
	assert {_a} is false with "'else if any' did not run when preceding 'if' was false and at least one condition was true"

test "SecConditional - else if any false":
	if:
		1 is 2
		2 is 7
	then:
		set {_b} to true
	else if any:
		1 is 8
		2 is 7
	then:
		set {_a} to false
	assert {_a} is not set with "'else if any' ran even though all conditions were false"

test "SecConditional - else if all false":
	if:
		1 is 2
		2 is 7
	then:
		set {_b} to true
	else if:
		1 is 8
		2 is 7
	then:
		set {_a} to false
	assert {_a} is not set with "'else if all' ran even though all conditions were false"
